### ISSUE TITLE
Layer Bearer Token

### ISSUE THREAD

**Issue by bennettl** [layerhq/node-layer-webhooks-services#12]
In the Readme, it specifies using the `LAYER_BEARER_TOKEN`, but it's not entirely clear where can we find the `LAYER_BEARER_TOKEN` ? In the dashboard, there is a sample token under "Platform API", which I'm not sure is the same as the webhooks

**Comment by michaelkantor** [comment]
The Platform API Token is used for both Platform API and Webhooks API.
