### ISSUE TITLE
Signature validation fails if the payload contains an emoji

### ISSUE THREAD

**Issue by nihalgonsalves** [layerhq/node-layer-webhooks-services#13]
This is the code:

```js
      var payload = JSON.stringify(req.body);
      var utf8safe = unescape(encodeURIComponent(payload));
      var hash = crypto.createHmac('sha1', secret).update(utf8safe).digest('hex');
```

Removing the utf8safe conversion fixes this, but are there any other concerns if that is done?

```js
      var payload = JSON.stringify(req.body);
      var hash = crypto.createHmac('sha1', secret).update(payload).digest('hex');
```

**Comment by michaelkantor** [comment]
There were UTF8 characters such as accents that failed to validate without that line...

Try validating the following message with and without that line:  "àn àccent is hàrd to pàrse".

Odd that emoji's don't work but accents do work...

**Comment by nihalgonsalves** [comment]
@michaelkantor I did test out some accented characters and it works (without the utf8safe conversion). I think Layer must be calculating the hash correctly for special characters (including Emoji) for the signature header now.

**Comment by michaelkantor** [comment]
Baffled.  Server engineer says nothing has changed, and he does remember the issue that required that line to be added.  So.  Lets work through a few possibilities.  To be clear, that line WAS added because certain UTF8 characters would cause validation to break.  Removing it should not be necessary, nor a valid option.

1. Put in logging when you change it to sanity check that its running with/without that line; sorry, but your result is unexpected and I want to insure sanity checking is done.
2. Is there anything in your system settings that may differ from others who have run this test?  Its a pain, but see if you can find any system settings for language, string types, etc... that may be non-standard.  Try setting `en-us` as your OS language, etc... and see if that changes anything.  Thats not a solution, but it would be good to know if somehow a difference in your environment contributes to changes in outcome.
3. Test with a range of UTF characters.  Do ALL emojis fail, or only the more recently added emojis?  Do lower value UTF-8 characters pass for you and higher value fail?

Sorry that this is a pain...

**Comment by lisbakke** [comment]
+1 We are having this issue too.

**Comment by lisbakke** [comment]
FYI we have some team members in Israel that had this issue and the solution was to make sure `English` is preferred language and to set Region to `United States`.

![screen shot 2017-03-22 at 10 17 01 am](https://cloud.githubusercontent.com/assets/982613/24208324/f529f326-0ee8-11e7-8cf0-6b9290a06b86.png)

**Comment by michaelkantor** [comment]
@nihalgonsalves Can you verify that this addresses your problem?  I don't like relying on this, but if this solves it, then we can work towards a long term solution with a better understanding of the problem.

**Comment by nihalgonsalves** [comment]
@michaelkantor I'm using a Docker container (node:6) so I doubt that it would matter, but I will check the container's locale again as well as verify the points you asked about earlier.

Stripping away the unicode characters during an _integrity/signature_ check seems like a terrible idea, especially if it additionally depends on the system locale.

**Comment by michaelkantor** [comment]
This does not strip them away; this insures that they are converted to a state comparable to the state the server has when IT generates the key.  What may  be needed is a way in node to test the environment settings and conditionally run that one line.

**Comment by lisbakke** [comment]
Hey @michaelkantor I thought we had the fix (by changing region) but it is still an issue. Did something change on Layer Server's auth signature lately? We didn't have these problems until recently.

This is a rough issue because it causes messages to be dropped and for the webhook to stop sending messages.

**Comment by wasauce** [comment]
+1 This issue is impacting us as well

**Comment by sk-eran** [comment]
+1 for us as well

**Comment by michaelkantor** [comment]
Wow.  Message is heard.  Let me see what I can figure out here.  The big challenge on my end will be replicating this in my environment.  I'll see if I can get this prioritized for next week.

**Comment by lisbakke** [comment]
@michaelkantor Try sending messages from the server that include one of these characters

```
const NOTE_ICON           = '\u{1F4DD}';
const RACKET_ICON         = '\u{1F3D3}';
const CONSTRUCTION_ICON   = '\u{1F477}';
const BOOKS_ICON          = '\u{1F4DA}';
const PHONE_RECEIVER_ICON = '\u{1F4DE}';
const LMK_ICON = '\u{1F4E2}';
const MOVIE_ICON = '\u{1F3A5}';
const WINEGLASS_ICON = '\u{1F377}';
const CHERRY_ICON = '\u{1F352}';
const CHECKMARK_ICON = '\u2705';
```

Also try copy / pasting a single quote character from a Google Word Doc and send that in a string. They are a different character than the normal single quote.

Let me know if that helps.

**Comment by nihalgonsalves** [comment]
@michaelkantor 

Here is the single file I'm using (extracted from the app I'm building) to test out this stuff. Try running it in a Docker `node` container to have a consistent environment / locale.

```es6

import url from 'url';
import path from 'path';
import crypto from 'crypto';
import express from 'express';
import bodyParser from 'body-parser';

const app = express();

app.get('/webhook', (req, res, next) => {
  const challenge = req.query.verification_challenge;
  if (challenge) {
    console.log('Received verification_challenge from Layer server.');
    res.status(200).send(challenge);
  } else {
    next();
  }
});

const verify = (req, res, next) => {
  const payload = JSON.stringify(req.body);
  // const utf8safe = unescape(encodeURIComponent(payload));
  const hash = crypto.createHmac('sha1', secret).update(payload).digest('hex');
  const signature = req.get('layer-webhook-signature');
  if (hash === signature) {
    next();
  } else {
    console.error('Incoming webhook signature invalid.');
    res.sendStatus(403);
  }
};

const webhookParser = bodyParser.json({ type: 'application/vnd.layer.webhooks+json' });

app.post('/webhook', webhookParser, verify, (req, res) => {
  // ... do something ...
  res.sendStatus(204);
});

app.listen(8000, () => console.log('Running.'));
```

**Comment by sk-eran** [comment]
@michaelkantor Can you please let us know where this stands? We have reverted to code that we *know* previously worked and the problem persists. This is a production grade issue for us, and we think this indicates a change in the signing of the server.
When can we expect an estimation for a timeframe for this issue?

**Comment by lisbakke** [comment]
@michaelkantor @nihalgonsalves @sk-eran

I may have found something. What version of node are you guys running?

On node `4.1.2` I am **not** seeing this issue. On node `7.7.1` I **am** seeing this issue. Could the `crypto` package have changed? Or something else to do with encoding? Or (very unlikely) somehow the `unescape` or `encodeURIComponent` methods?

Can you guys confirm what I'm seeing with different node versions?

**Comment by michaelkantor** [comment]
@sk-eran Verified report from @lisbakke that there is a clear change in behavior based on node version.  Going to see if I can address this.

**Comment by sk-eran** [comment]
@michaelkantor Thanks! Waiting eagerly for your update :)

**Comment by michaelkantor** [comment]
@sk-eran @lisbakke @nihalgonsalves npm has been updated; marking this as closed... pending feedback telling me I've missed something.

Node versions up to version 5 required special handling for calculating the signature; versions 6 and up did not need this.

**Comment by lisbakke** [comment]
Nice one @michaelkantor!!! `1.0.7` Fixes it!

**Comment by sk-eran** [comment]
Thanks!!!!!
